### ISSUE TITLE
`pod update` fails with when art repos exist

### ISSUE THREAD

**Issue by alwold** [jfrog/cocoapods-art#15]
- Fresh install of cocoapods 1.3.1
- Fresh install of cocoapods-art 1.0.0
- Add an artifactory repo with `pod repo-art add`
- Run `pod update` on a project
- Fails with the error below

It looks like the `update_repositories` method in `analyzer.rb` in cocoapods 1.3.1 is checking each repo to see if it is a git-based repo. Since `ArtSource` does not implement the `git?` method, it uses the default which tries to run git commands on the directory, which does not exist, causing it to fail.

```
$ pod update --verbose
Update all pods
  Preparing
  - Running source provider hooks
    - cocoapods-art from `/Users/alwold/.rvm/gems/ruby-2.4.2/gems/cocoapods-art-1.0.0/lib/cocoapods_plugin.rb`
      cocoapods-art received source_provider hook
/Users/alwold/.cocoapods/repos-art/xxx-specs/.artpodrc

Updating local specs repositories
fatal: Cannot change to '/Users/alwold/.cocoapods/repos/xxx-specs': No such file or directory
[!] The `xxx-specs` repo is not a git repo.

/Users/alwold/.rvm/gems/ruby-2.4.2/gems/cocoapods-core-1.3.1/lib/cocoapods-core/source/manager.rb:318:in `git_source_named'
/Users/alwold/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.3.1/lib/cocoapods/sources_manager.rb:80:in `update'
/Users/alwold/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.3.1/lib/cocoapods/installer/analyzer.rb:237:in `block in update_repositories'
/Users/alwold/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.3.1/lib/cocoapods/installer/analyzer.rb:235:in `each'
/Users/alwold/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.3.1/lib/cocoapods/installer/analyzer.rb:235:in `update_repositories'
/Users/alwold/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:150:in `block in resolve_dependencies'
/Users/alwold/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.3.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/alwold/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:149:in `resolve_dependencies'
/Users/alwold/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:116:in `install!'
/Users/alwold/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.3.1/lib/cocoapods/command/update.rb:81:in `run'
/Users/alwold/.rvm/gems/ruby-2.4.2/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/alwold/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.3.1/lib/cocoapods/command.rb:52:in `run'
/Users/alwold/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.3.1/bin/pod:55:in `<top (required)>'
/Users/alwold/.rvm/gems/ruby-2.4.2/bin/pod:23:in `load'
/Users/alwold/.rvm/gems/ruby-2.4.2/bin/pod:23:in `<main>'
/Users/alwold/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `eval'
/Users/alwold/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by yuhanle** [comment]
Use cocoapods-art 0.9.4

**Comment by choli** [comment]
Is this really the best solution? Or will there be a release of 1.0.1 anytime soon?
