### ISSUE TITLE
When a repo name is provided, `pod repo-art lint` fails.

### ISSUE THREAD

**Issue by dla0510** [jfrog/cocoapods-art#68]
### Plugins

```
cocoapods-art         : 1.1.1
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Error

```
NoMethodError - undefined method `each' for an instance of Pod::ArtifactoryRepo
/opt/homebrew/lib/ruby/gems/3.3.0/gems/cocoapods-art-1.1.1/lib/pod/command/repo_art/lint.rb:37:in `run'
/opt/homebrew/lib/ruby/gems/3.3.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/opt/homebrew/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:52:in `run'
/opt/homebrew/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/bin/pod:55:in `<top (required)>'
/opt/homebrew/lib/ruby/gems/3.3.0/bin/pod:25:in `load'
/opt/homebrew/lib/ruby/gems/3.3.0/bin/pod:25:in `<main>'
```

**Comment by dla0510** [comment]
I reviewed the code and it seems that the issue arose from calling the 'each' function on an instance variable instead of an array. 
I have made the necessary changes to the code and created a pull request. 
I would appreciate it if you could take a look.
